test

diff --git a/.github/workflows/ci-alpine-build.yml b/.github/workflows/ci-alpine-build.yml
--- a/.github/workflows/ci-alpine-build.yml
+++ b/.github/workflows/ci-alpine-build.yml
@@ -1,4 +1,3 @@
-# @credits https://github.com/c0re100/qBittorrent-Enhanced-Edition
 name: ci - alpine build
 
 on:
@@ -24,36 +23,21 @@ on:
         description: "script name"
         required: true
         type: string
+
 jobs:
-  build-alpine:
-    runs-on: ubuntu-24.04-arm
+  build:
+    runs-on: ${{ matrix.runs_on }}
     strategy:
       fail-fast: false
       matrix:
+        runs_on: ["ubuntu-24.04-arm"]
         os_id: [alpine]
         os_version_id: [edge]
         qbt_cross_name:
-          [
-            "armel",
-            "armhf",
-            "armv7",
-            "aarch64",
-            "x86_64",
-            "x86",
-            "s390x",
-            "powerpc",
-            "ppc64el",
-            "mips",
-            "mipsel",
-            "mips64",
-            "mips64el",
-            "riscv64",
-          ]
+          ["armel", "armhf", "armv7", "aarch64", "riscv64", "x86_64", "x86", "s390x", "powerpc", "ppc64el", "mips", "mipsel", "mips64", "mips64el"]
         qbt_libtorrent_version: ["1.2"]
-        qbt_libtorrent_tag: [""]
         qbt_build_tool: ["qmake"]
         qbt_qbittorrent_tag: ["release-4.3.9"]
-        qbt_boost_tag: [""]
         include:
           - qbt_build_tool: "qmake"
             qbt_qt_version_name: ""
@@ -67,7 +51,10 @@ jobs:
       set_skip_icu: ${{ inputs.icu }}
       set_workflow_files: ${{ inputs.workflow-files }}
       set_build_debug: ${{ inputs.debug }}
-      set_qbt_mcm_url: "userdocs/qbt-musl-cross-make-test"
+      set_qbt_mcm_url: "" # default is userdocs/qbt-musl-cross-make
+      set_qbt_with_qemu: "" # default is yes
+      set_qbt_host_deps: "" # default is no
+      set_qbt_host_deps_repo: "" # default is userdocs/qbt-host-deps
 
     steps:
       - name: Checkout ${{ inputs.distinct_id }}
@@ -77,8 +64,8 @@ jobs:
 
       - name: Download qbt-nox-static.bash
         run: |
-          curl -LO https://raw.githubusercontent.com/userdocs/qbittorrent-nox-static-test/refs/heads/main/qbt-nox-static.bash
-          chmod +x qbt-nox-static.bash
+          curl -LO "https://raw.githubusercontent.com/userdocs/qbittorrent-nox-static/refs/heads/main/${script_name}"
+          chmod +x "${script_name}"
 
       - name: Host - Create Docker template env file ${{ inputs.distinct_id }}
         run: |
@@ -104,66 +91,51 @@ jobs:
           printf '%s\n' "qbt_standard=" >> env.custom
           printf '%s\n' "qbt_static_ish=" >> env.custom
           printf '%s\n' "qbt_optimise=${qbt_optimise}" >> env.custom
-          printf '%s\n' "qbt_host_deps_qt6=${qbt_host_deps_qt6}" >> env.custom
-          printf '%s\n' "qbt_host_deps_full=${qbt_host_deps_full}" >> env.custom
-          printf '%s\n' "qbt_host_deps_path=${qbt_host_deps_path}" >> env.custom
-          printf '%s\n' "qbt_host_deps_url=${qbt_host_deps_url}" >> env.custom
-          printf '%s\n' "qbt_host_deps_repo=${qbt_host_deps_repo}" >> env.custom
+          printf '%s\n' "qbt_with_qemu=${set_qbt_with_qemu}" >> env.custom
+          printf '%s\n' "qbt_host_deps=${set_qbt_host_deps}" >> env.custom
+          printf '%s\n\n' "qbt_host_deps_repo=${set_qbt_host_deps_repo}" >> env.custom
 
-      # - name: Host - Github env to container ${{ inputs.distinct_id }}
-      #   run: env >> env.custom
-
-      - name: Host - check stuff ${{ inputs.distinct_id }}
-        run: export $(cat env.custom) && bash ${script_name}
-
-      - name: Host - qBittorrent v5 transition ${{ inputs.distinct_id }}
+      - name: Host - Debian based specific env ${{ inputs.distinct_id }}
+        if : matrix.os_id != 'alpine'
         run: |
-          if [[ -f "${qbt_build_dir}/release_info/disable-qt5" || -f "disable-qt5" ]]; then
-              printf '%s\n' "disable_qt5=yes" >> $GITHUB_ENV
-              printf '%s\n' "Found file: \`disable-qt5\` -> setting env: \`disable_qt5=yes\`" >> $GITHUB_STEP_SUMMARY
-          fi
+          printf '%s\n' "LANG=C.UTF-8" >> env.custom
+          printf '%s\n' "LC_ALL=C.UTF-8" >> env.custom
+          printf '%s\n\n' "DEBIAN_FRONTEND=noninteractive" >> env.custom
 
-      - name: Host - phased updates ${{ inputs.distinct_id }}
-        run: printf '%s\n' 'APT::Get::Always-Include-Phased-Updates "false";' | sudo tee /etc/apt/apt.conf.d/99-phased-updates
+      - name: Host - Bootstrap qemu
+        uses: userdocs/actions/qemu@main
 
-      - name: Host - update ${{ inputs.distinct_id }}
-        run: sudo apt-get update
-
-      # - name: Host - upgrade ${{ inputs.distinct_id }}
-      #   run: sudo apt-get -y upgrade
-
-      - name: Host - set up qemu-user-static binfmt-support ${{ inputs.distinct_id }}
-        run: sudo apt install qemu-user-static binfmt-support
-
-      - name: Host - Create docker ${{ env.multiarch }} container ${{ inputs.distinct_id }}
-        run: |
-          # We create an Alpine edge container for cross-compilation with a user named gh which has same id as runner 1001 and provide sudo access
-          # This way we can run commands as a non-root user, avoiding permission issues on host runner. Switching between user and root as needed.
-          docker run --name ${container_name} -it -d --env-file env.custom -w /home/gh -v ${{ github.workspace }}:/home/gh ${{ matrix.os_id }}:${{ matrix.os_version_id }}
-          # Create the user gh with the id 1001:1001 which is the same as the runner user id and group id.
-          docker exec ${container_name} sh -c 'adduser -h /home/gh -Ds /bin/bash -u 1001 gh && apk add sudo'
-          # Allow the user gh to run sudo without password prompt: docker exec -u gh:gh ${container_name} sudo ls
-          docker exec ${container_name} sh -c 'printf "%s" "gh ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/gh'
+      - uses: userdocs/actions/qbt_docker@main
+        with:
+            # if the env.custom file exists, it will be used to pass environment
+            distinct_id: ${{ inputs.distinct_id }}
+            use_host_env: "false"
+            container_name: ${{ env.container_name }}
+            os_id: ${{ matrix.os_id }}
+            os_version_id: ${{ matrix.os_version_id }}
+            custom_docker_commands: ""
+            additional_alpine_apps: "bash curl git"
+            additional_debian_apps: "bash curl git"
 
       - name: Host - patches ${{ inputs.distinct_id }}
         run: mkdir -p ${qbt_build_dir}/patches && cp -r patches/* ${qbt_build_dir}/patches/
 
-      - name: Docker - apk update ${{ inputs.distinct_id }}
-        run: docker exec ${container_name} apk update
-
-      - name: Docker - apk install bash ${{ inputs.distinct_id }}
-        run: docker exec ${container_name} apk add bash
-
-      - name: Docker - Bootstrap test tools ${{ inputs.distinct_id }}
+      - name: Docker - bootstrap_deps ${{ inputs.distinct_id }}
+        if: inputs.script_name == 'qbt-nox-static.bash'
         run: docker exec ${container_name} bash ${script_name} bootstrap_deps
 
       - name: Docker - Bootstrap build ${{ inputs.distinct_id }}
         run: docker exec -u gh:gh ${container_name} bash ${script_name} -bs-a
 
-      - name: Docker - zlib-ng ${{ inputs.distinct_id }}
+      - name: Docker - glibc ${{ inputs.distinct_id }}
+        if : matrix.os_id != 'alpine'
+        run: docker exec -u gh:gh ${container_name} bash ${script_name} glibc
+
+      - name: Docker - zlib ${{ inputs.distinct_id }}
         run: docker exec -u gh:gh ${container_name} bash ${script_name} zlib
 
       - name: Docker - iconv ${{ inputs.distinct_id }}
+        if: matrix.qbt_libtorrent_version == '1.2'
         run: docker exec -u gh:gh ${container_name} bash ${script_name} iconv
 
       - name: Docker - icu ${{ inputs.distinct_id }}
@@ -180,7 +152,7 @@ jobs:
         run: docker exec -u gh:gh ${container_name} bash ${script_name} libtorrent
 
       - name: Docker - double_conversion ${{ inputs.distinct_id }}
-        if: matrix.qbt_build_tool == '' && env.disable_qt5 != 'yes'
+        if: matrix.qbt_build_tool == ''
         run: docker exec -u gh:gh ${container_name} bash ${script_name} double_conversion
 
       - name: Docker - qtbase ${{ inputs.distinct_id }}
@@ -204,7 +176,7 @@ jobs:
         run: docker exec -u gh:gh -w /home/gh/${{ env.qbt_build_dir }}/release_info ${container_name} bash -c 'mv *.md *.json '/home/gh/${{ env.qbt_build_dir }}/completed''
 
       - name: Host - Upload libtorrent-v${{ matrix.qbt_libtorrent_version }}-qbittorrent-nox and release info artifact ${{ inputs.distinct_id }}
-        if: success() && env.disable_qt5 != 'yes'
+        if: success()
         uses: actions/upload-artifact@v4
         with:
           name: libtorrent-v${{ matrix.qbt_libtorrent_version }}-${{ matrix.qbt_cross_name }}-${{ matrix.qbt_qt_version_name }}qbittorrent-nox
@@ -213,15 +185,15 @@ jobs:
             !${{ env.qbt_build_dir }}/completed/*.png
 
       - name: Host - Upload cmake graphs artifact ${{ inputs.distinct_id }}
-        if: success() && matrix.qbt_build_tool == '' && env.disable_qt5 != 'yes'
+        if: success() && matrix.qbt_build_tool == ''
         uses: actions/upload-artifact@v4
         with:
           name: "${{ matrix.qbt_cross_name }}-libtorrent-v${{ matrix.qbt_libtorrent_version }}-graphs"
           path: "${{ env.qbt_build_dir }}/completed/*.png"
 
-      - name: Host - Upload build dir on error or cancel
-        if: ( cancelled() || failure() ) && env.disable_qt5 != 'yes'
-        uses: actions/upload-artifact@v4
-        with:
-          name: "${{ matrix.qbt_cross_name }}-libtorrent-v${{ matrix.qbt_libtorrent_version }}-logs"
-          path: "${{ env.qbt_build_dir }}"
+      # - name: Host - Upload build dir on error or cancel
+      #   if: ( cancelled() || failure() )
+      #   uses: actions/upload-artifact@v4
+      #   with:
+      #     name: "${{ matrix.qbt_cross_name }}-libtorrent-v${{ matrix.qbt_libtorrent_version }}-logs"
+      #     path: "${{ env.qbt_build_dir }}"
